# Site Settings
title: Ihsan Ullah
description: Research Fellow @ CCG | DGIST
logo: /assets/img/headshot.jpg
baseurl: ""
url: "https://ihsan149.github.io"
lang: en-US
timezone: Asia/Seoul

# Google Analytics
# Optional
google_analytics: G-DYKEMKK790  # GA4 tracking ID

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
safe: true
lsi: false

# Plugin Settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO Settings
author: Ihsan Ullah
twitter:
  username: ihsan_ullah
  card: summary_large_image
social:
  name: Ihsan Ullah
  links:
    - https://scholar.google.com/citations?user=eod9uX0AAAAJ&hl=en
    - https://www.linkedin.com/in/ihsan-ullah-phd-83b4a1104/
    - https://github.com/ihsan149

# Collections
collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - test.sh
  - run.sh
